# Generated by Django 3.2.8 on 2021-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
