# Generated by Django 3.2.8 on 2021-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonsult_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
