# Generated by Django 3.2.9 on 2021-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonsult_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
